name: API call
on:
  #push:
  # branches: [ "main" ]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          CONTAINER_PATH: ${{ secrets.CONTAINER_PATH }}
        with:
          host: ${{ secrets.SITEHOST_HOST }}
          username: ${{ secrets.SITEHOST_USER }}
          password: ${{ secrets.SITEHOST_PASSWORD }}
          port: 22
          debug: enable
          script: |
            echo "Setup" 
  #          cd $CONTAINER_PATH
  #          git pull
  #          yarn install
  #          yarn run build
      - name: API Call
        uses: appleboy/ssh-action@master
        env: 
          SITEHOST_API_KEY: ${{ secrets.SITEHOST_API_KEY }}
          SITEHOST_CLIENT_ID: ${{ secrets.SITEHOST_CLIENT_ID }}
          SITEHOST_SERVER: ${{ secrets.SITEHOST_SERVER }}
          SITEHOST_NAME: ${{ secrets.SITEHOST_NAME }}
          SITEHOST_CONTAINERS: ${{ secrets.SITEHOST_CONTAINERS }}
        with:
          host: ${{ secrets.SITEHOST_HOST }}
          username: ${{ secrets.SITEHOST_USER }}
          password: ${{ secrets.SITEHOST_PASSWORD }}
          env: SITEHOST_API_KEY,SITEHOST_CLIENT_ID,SITEHOST_SERVER,SITEHOST_NAME,SITEHOST_CONTAINERS
          port: 22
          debug: enable
          script: |
              curl --location --request POST "https://api.sitehost.nz/1.1/cloud/stack/restart.json" \
              --header 'Content-Type: application/json' \
              --data-raw '{
                  "apikey": $SITEHOST_API_KEY,
                  "client_id": $SITEHOST_CLIENT_ID,
                  "server": $SITEHOST_SERVER,
                  "name": $SITEHOST_NAME,
                  "container[]": $SITEHOST_CONTAINERS
              }'

            
            
      
