name: API call
on:
  push:
  # branches: [ "main" ]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SITEHOST_HOST }}
          username: ${{ secrets.SITEHOST_USER }}
          password: ${{ secrets.SITEHOST_PASSWORD }}
          port: 22
          script: |
            echo "Test" 
            which python
  #          cd ${{ CONTAINER_PATH }}
  #          git pull
  #          yarn install
  #          yarn run build
      - name: API Call
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SITEHOST_HOST }}
          username: ${{ secrets.SITEHOST_USER }}
          password: ${{ secrets.SITEHOST_PASSWORD }}
          port: 22
          script: |
            echo "python"
          shell: python3
            
            
      
